"""Update theme table

Revision ID: 3614c2d1b137
Revises: e3ee3e6eb002
Create Date: 2024-02-15 12:27:14.214307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3614c2d1b137'
down_revision = 'e3ee3e6eb002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('backgroundColor', sa.String(), nullable=True))
        batch_op.alter_column('color',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theme', schema=None) as batch_op:
        batch_op.alter_column('color',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('backgroundColor')
        batch_op.drop_column('theme')

    # ### end Alembic commands ###
