"""Rename new team columns to old column names

Revision ID: 5b4341a2a977
Revises: 79059b0da3e4
Create Date: 2024-03-23 20:46:53.167223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b4341a2a977'
down_revision = '79059b0da3e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bracket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('winner', sa.Integer(), nullable=True))
        batch_op.drop_constraint('bracket_winner_team_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'bracket_team', ['winner'], ['id'])
        batch_op.drop_column('winner_team')

    with op.batch_alter_table('correct_bracket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('winner', sa.Integer(), nullable=True))
        batch_op.drop_constraint('correct_bracket_winner_team_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'bracket_team', ['winner'], ['id'])
        batch_op.drop_column('winner_team')

    with op.batch_alter_table('correct_game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('winner', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('loser', sa.Integer(), nullable=True))
        batch_op.drop_constraint('correct_game_winner_team_fkey', type_='foreignkey')
        batch_op.drop_constraint('correct_game_loser_team_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'bracket_team', ['winner'], ['id'])
        batch_op.create_foreign_key(None, 'bracket_team', ['loser'], ['id'])
        batch_op.drop_column('loser_team')
        batch_op.drop_column('winner_team')

    with op.batch_alter_table('default_game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('away', sa.Integer(), nullable=True))
        batch_op.drop_constraint('default_game_away_team_fkey', type_='foreignkey')
        batch_op.drop_constraint('default_game_home_team_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'bracket_team', ['home'], ['id'])
        batch_op.create_foreign_key(None, 'bracket_team', ['away'], ['id'])
        batch_op.drop_column('away_team')
        batch_op.drop_column('home_team')

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('winner', sa.Integer(), nullable=True))
        batch_op.drop_constraint('game_winner_team_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'bracket_team', ['winner'], ['id'])
        batch_op.drop_column('winner_team')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('winner_team', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('game_winner_team_fkey', 'bracket_team', ['winner_team'], ['id'])
        batch_op.drop_column('winner')

    with op.batch_alter_table('default_game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_team', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('away_team', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('default_game_home_team_fkey', 'bracket_team', ['home_team'], ['id'])
        batch_op.create_foreign_key('default_game_away_team_fkey', 'bracket_team', ['away_team'], ['id'])
        batch_op.drop_column('away')
        batch_op.drop_column('home')

    with op.batch_alter_table('correct_game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('winner_team', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('loser_team', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('correct_game_loser_team_fkey', 'bracket_team', ['loser_team'], ['id'])
        batch_op.create_foreign_key('correct_game_winner_team_fkey', 'bracket_team', ['winner_team'], ['id'])
        batch_op.drop_column('loser')
        batch_op.drop_column('winner')

    with op.batch_alter_table('correct_bracket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('winner_team', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('correct_bracket_winner_team_fkey', 'bracket_team', ['winner_team'], ['id'])
        batch_op.drop_column('winner')

    with op.batch_alter_table('bracket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('winner_team', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('bracket_winner_team_fkey', 'bracket_team', ['winner_team'], ['id'])
        batch_op.drop_column('winner')

    # ### end Alembic commands ###
