"""Remove old team columns

Revision ID: 79059b0da3e4
Revises: f52c832eca08
Create Date: 2024-03-23 20:44:41.520026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79059b0da3e4'
down_revision = 'f52c832eca08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bracket', schema=None) as batch_op:
        batch_op.drop_column('winner')

    with op.batch_alter_table('correct_bracket', schema=None) as batch_op:
        batch_op.drop_column('winner')

    with op.batch_alter_table('correct_game', schema=None) as batch_op:
        batch_op.drop_column('loser')
        batch_op.drop_column('winner')

    with op.batch_alter_table('default_game', schema=None) as batch_op:
        batch_op.drop_column('away')
        batch_op.drop_column('home')

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('winner')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('winner', sa.VARCHAR(length=30), autoincrement=False, nullable=True))

    with op.batch_alter_table('default_game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('away', sa.VARCHAR(length=30), autoincrement=False, nullable=True))

    with op.batch_alter_table('correct_game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('winner', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('loser', sa.VARCHAR(length=30), autoincrement=False, nullable=True))

    with op.batch_alter_table('correct_bracket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('winner', sa.VARCHAR(length=30), autoincrement=False, nullable=True))

    with op.batch_alter_table('bracket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('winner', sa.VARCHAR(length=30), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
