"""Add rank to bracket

Revision ID: a7c2f6dffa90
Revises: 07f658a4580b
Create Date: 2023-02-05 14:24:59.219083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7c2f6dffa90'
down_revision = '07f658a4580b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bracket', sa.Column('rank', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bracket', 'rank')
    # ### end Alembic commands ###
