"""Store points per round

Revision ID: e3ee3e6eb002
Revises: a7c2f6dffa90
Create Date: 2023-03-27 14:54:53.272500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3ee3e6eb002'
down_revision = 'a7c2f6dffa90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bracket', sa.Column('r1', sa.Integer(), nullable=True))
    op.add_column('bracket', sa.Column('r2', sa.Integer(), nullable=True))
    op.add_column('bracket', sa.Column('r3', sa.Integer(), nullable=True))
    op.add_column('bracket', sa.Column('r4', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bracket', 'r4')
    op.drop_column('bracket', 'r3')
    op.drop_column('bracket', 'r2')
    op.drop_column('bracket', 'r1')
    # ### end Alembic commands ###
