"""Add new team model to db

Revision ID: f52c832eca08
Revises: c28b624586e0
Create Date: 2024-03-22 22:50:41.895335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f52c832eca08'
down_revision = 'c28b624586e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bracket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('winner_team', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'bracket_team', ['winner_team'], ['id'])

    with op.batch_alter_table('correct_bracket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('winner_team', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'bracket_team', ['winner_team'], ['id'])

    with op.batch_alter_table('correct_game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('winner_team', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('loser_team', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'bracket_team', ['winner_team'], ['id'])
        batch_op.create_foreign_key(None, 'bracket_team', ['loser_team'], ['id'])

    with op.batch_alter_table('default_game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_team', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('away_team', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'bracket_team', ['home_team'], ['id'])
        batch_op.create_foreign_key(None, 'bracket_team', ['away_team'], ['id'])

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('winner_team', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'bracket_team', ['winner_team'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('winner_team')

    with op.batch_alter_table('default_game', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('away_team')
        batch_op.drop_column('home_team')

    with op.batch_alter_table('correct_game', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('loser_team')
        batch_op.drop_column('winner_team')

    with op.batch_alter_table('correct_bracket', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('winner_team')

    with op.batch_alter_table('bracket', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('winner_team')

    # ### end Alembic commands ###
